#Variables
@baseUrl = http://localhost:3333

#Health check
# @name healthCheck
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}

###
@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create questions
# @name createQuestion
POST {{baseUrl}}/rooms/043db7b3-344c-44d3-b478-473995761715/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}